### ISSUE TITLE
启动初始化时可以同时取回多个namespace的配置吗？

### ISSUE THREAD

**Issue by xieyihao** [xuezier/egg-apollo-client#14]
如题，业务按分类配置了多个namespace，可以在应用启动时（init_on_start=true），从Apollo取回多个namespace的配置吗？

**Comment by xuezier** [comment]
可以参考文档`启动自定义`那一栏
https://github.com/xuezier/egg-apollo-client#%E5%90%AF%E5%8A%A8%E8%87%AA%E5%AE%9A%E4%B9%89

在启动时可以多次调用 `init` 方法，内部会自动分配多个 `namespace` 存储，取配置的时候参考文档如何从 namespace 拿数据
