### ISSUE TITLE
获取apollo接口的时候会提示报错

### ISSUE THREAD

**Issue by XcGuaN-miepia** [xuezier/egg-apollo-client#20]
版本：2.0.3
config.apollo = {
  config_server_url: 'http://106.54.227.205:8080',
  app_id: 'demo001',
  init_on_start: true,
};
请求地址我看了一下是http://106.54.227.205:8080/configs/demo001/default/application
在浏览器中能直接打开，在node当中有报错
2021-05-27 18:18:24,247 WARN 35971 [egg-apollo-client] {"message":"RequestError: undefined"}
在版本1.4.0当中我也尝试过，是可以获取到配置的

**Comment by xuezier** [comment]
原版本不支持自定义 port 配置，已在新版本中添加支持

fixed in: v2.0.4
