### ISSUE TITLE
set_env_file not work

### ISSUE THREAD

**Issue by imapolaris** [xuezier/egg-apollo-client#21]
```
apollo: {
      config_server_url: 'server_url',
      app_id: 'appId',
      init_on_start: true,
      cluster_name: 'default',
      namespace_name: 'application',
      release_key: '',
      set_env_file: true,
      watch: true,
      timeout: 5000,
},
```

this is my config, built **.env.apollo** file under the **app.baseDir** yet.
set_env_file not work, what is the problem?

**Comment by imapolaris** [comment]
i config the env_file_path, resolve this problem. why env_file_path default config  not work?

**Comment by xuezier** [comment]
`env_file_path` default value is: `os.tmpdir()`

**Comment by xuezier** [comment]
`env_file_path` default value is: `os.tmpdir()` , it's  a mistake in `readme`

**Comment by imapolaris** [comment]
> `env_file_path` default value is: `os.tmpdir()` , it's a mistake in `readme`

ok, i find it. appreciate!
