### ISSUE TITLE
how to receive watch result

### ISSUE THREAD

**Issue by imapolaris** [xuezier/egg-apollo-client#22]
i config watch:true, timeout:5.
but i dont know whether they worked.
how can i receive the long polling result?

**Comment by xuezier** [comment]
try it in beforeStart
```ts
apollo.on('config.updated', (data: IApolloReponseConfigData) => {
    // do something here
})

interface IApolloReponseConfigData {
    // '{"appId":"ums-local","cluster":"default","namespaceName":"application","configurations":{"NODE_ENV":"production"}
    appId: string;
    cluster: string;
    namespaceName: string;
    configurations: {
        [x: string]: string;
    };
    releaseKey: string;
}
```

**Comment by imapolaris** [comment]
> try it in beforeStart
> 
> ```ts
> apollo.on('config.updated', (data: IApolloReponseConfigData) => {
>     // do something here
> })
> 
> interface IApolloReponseConfigData {
>     // '{"appId":"ums-local","cluster":"default","namespaceName":"application","configurations":{"NODE_ENV":"production"}
>     appId: string;
>     cluster: string;
>     namespaceName: string;
>     configurations: {
>         [x: string]: string;
>     };
>     releaseKey: string;
> }
> ```

thx, it works.
